CREATE DATABASE IF NOT EXISTS faculdadeHepta;

USE faculdadeHepta;


CREATE TABLE ESTUDANTE (
    idEstudante INTEGER(2) NOT NULL AUTO_INCREMENT,
    nomeCompleto VARCHAR(100) NOT NULL,
    
	CONSTRAINT ESTUDANTE_PK
    PRIMARY KEY (idEstudante)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1;


CREATE TABLE PROFESSOR (
    idProfessor INTEGER(2) NOT NULL AUTO_INCREMENT,
    nomeCompleto VARCHAR(100) NOT NULL,
    
    CONSTRAINT PROFESSOR_PK
    PRIMARY KEY (idProfessor)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1;


CREATE TABLE DISCIPLINA (
    idDisciplina INTEGER(2) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    ementaArquivo LONGBLOB,
    ementaNomeArquivo VARCHAR(30),
    ementaTipoArquivo VARCHAR(10),
    idProfessor INTEGER(2) NOT NULL,
    
    CONSTRAINT DISCIPLINA_PK
    PRIMARY KEY (idDisciplina),
    
    CONSTRAINT DISCIPLINA_PROFESSOR_FK
    FOREIGN KEY (idProfessor)
    REFERENCES PROFESSOR (idProfessor)
    ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1;


CREATE TABLE cursa (
    idEstudante INTEGER(2) NOT NULL,
    idDisciplina INTEGER(2) NOT NULL,
    
    CONSTRAINT cursa_ESTUDANTE_FK
    FOREIGN KEY (idEstudante)
    REFERENCES ESTUDANTE (idEstudante)
    ON DELETE RESTRICT,
    
    CONSTRAINT cursa_DISCIPLINA_FK
    FOREIGN KEY (idDisciplina)
    REFERENCES DISCIPLINA (idDisciplina)
    ON DELETE RESTRICT
) ENGINE = InnoDB;
