CREATE DATABASE IF NOT EXISTS faculdadeHepta;

USE faculdadeHepta;


CREATE TABLE PROFESSOR (
    idProfessor INTEGER(2) NOT NULL AUTO_INCREMENT,
    nomeCompleto VARCHAR(100) NOT NULL,
    
    CONSTRAINT PROFESSOR_PK
    PRIMARY KEY (idProfessor)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1;


CREATE TABLE DISCIPLINA (
    idDisciplina INTEGER(2) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    planoEnsinoArquivo LONGBLOB,
    planoEnsinoNome VARCHAR(100),
    idProfessor INTEGER(2) NOT NULL,
    
    CONSTRAINT DISCIPLINA_PK
    PRIMARY KEY (idDisciplina),
    
    CONSTRAINT DISCIPLINA_PROFESSOR_FK
    FOREIGN KEY (idProfessor)
    REFERENCES PROFESSOR (idProfessor)
    ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1;
